unique_ids:
  assets:
    standard-page.html: HJ3ZACHHIKNYDNTFZJDH6PYC4KZCCW7P
    theme.css: HWTNWZLWIHYN4DHK3SWA7J36F7IA7YGT
  forms:
    Form1: AHV36GE3WSYWY7XK4VWDGR2I7ILX5Y2A
  modules: {}
  scripts: {}
  server_modules: {}
